apiVersion: apps/v1
kind: Deployment
metadata: 
    name: uppics-depl
    labels: 
        ms: uppics
spec: 
    replicas: 1
    revisionHistoryLimit: 0
    selector:
        matchLabels:
            ms: uppics
    template:
        metadata:
            labels: 
                ms: uppics
        spec: 
            containers: 
                - name: uppics
                  image: nicolasances/uppics:1.0.1
                  ports: 
                    - containerPort: 8080
                  env:
                      - name: UPPICS_ROOT
                        value: /uppics-data
                      - name: UPPICS_TMP
                        value: /uppics-data/tmp
                  volumeMounts:
                      - name: local-disk-strategy-vol
                        mountPath: /uppics-data
            volumes:
                - name: local-disk-strategy-vol
                  persistentVolumeClaim:
                      claimName: pvc-uppics