# Persistent Volume to support the local disk storage option
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-uppics
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: pd-uppics
---
# Persistent Volume Claim to claim that volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uppics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
